Repository Motion115/GistVis, pull requests merged in 2025-02, with the labels that each got.

#7 Custom model source
  .gitignore
  src/App.tsx
  src/components/LLMConf.tsx
  src/demo/Demo.tsx
  src/modules/llm/llm.ts
  src/style/page.css
  yarn.lock
Labels: feature

#8 Bump dependency
  .gitignore
  babel.config.js
  jest.config.js
  package.json
  src/modules/llm/annotator/runTypeCheck.ts
  src/modules/llm/annotator/typeModerator.ts
  src/modules/llm/discoverer/discoverer.ts
  src/modules/llm/extractor/extractComparison.ts
  src/modules/llm/extractor/extractExtreme.ts
  src/modules/llm/extractor/extractProportion.ts
  src/modules/llm/extractor/extractRank.ts
  src/modules/llm/extractor/extractTrend.ts
  src/modules/llm/extractor/extractValue.ts
  tsconfig.json
  yarn.lock
Labels: refactor

#20 fix: environment variables reading error
  site/src/demo/LLMConf.tsx
  site/src/modules/llm/llm.ts
Labels: Bug 🐛

#27 Bugfix: regex match and overflow display
  site/src/demo/Demo.tsx
  site/src/demo/demoPage.tsx
  site/src/modules/visualizer/utils/fuzzySearch.ts
  site/src/modules/visualizer/widgets/hoverText.tsx
Labels: Bug 🐛, Area - Visualizer

#32 24 pipeline component
  site/.env.SAMPLE
  site/src/demo/Demo.tsx
  site/src/demo/pipeline/DemoPipeline.tsx
  site/src/demo/pipeline/PipelineExplorer.tsx
  site/src/demo/pipeline/SpecEditor.tsx
  site/src/demo/pipeline/SpecProcessEditor.tsx
  site/src/modules/llm/llm.ts
  site/src/modules/visualizer/renderer/renderer.tsx
Labels: Area - Site

#35 Bugfix: regex match
  site/src/modules/visualizer/utils/fuzzySearch.ts
Labels: Bug 🐛
