Repository Motion115/GistVis, pull requests merged in 2025-03, with the labels that each got.

#44 Visualizer modification: To support the invariant trend
  site/src/modules/visualizer/renderer/trendTextRenderer.tsx
  site/src/modules/visualizer/types.ts
  site/src/modules/visualizer/utils/utils.ts
  site/src/modules/visualizer/wordScaleVis/lineChart.tsx
Labels: Area - Visualizer

#41 Bugfix: VerticalBarChart Incorrectly Highlights Multiple Bars and Displays Inaccurate Tooltips Due to Insufficiently Unique Bar Identifiers
  site/src/modules/visualizer/wordScaleVis/vBarChart.tsx
Labels: Bug 🐛, Area - Site

#33 Bugfix: 31-wrong-article-title
  site/src/demo/Demo.tsx
  site/src/userstudy/articlePage.tsx
  site/src/userstudy/articles/articledata.ts
  site/src/userstudy/homePage.tsx
Labels: Bug 🐛

#50 Vake/visualizer2package/refactor to gistwsv
  package.json
  packages/gist-wsv/README.md
  packages/gist-wsv/package.json
  packages/gist-wsv/src/App.tsx
  packages/gist-wsv/src/components/llm/types.ts
  packages/gist-wsv/src/components/llm/visKB.ts
  packages/gist-wsv/src/components/visualizer/constants.ts
  packages/gist-wsv/src/components/visualizer/props.ts
  packages/gist-wsv/src/components/visualizer/renderer/comparisonTextRenderer.tsx
  packages/gist-wsv/src/components/visualizer/renderer/extremeTextRenderer.tsx
  packages/gist-wsv/src/components/visualizer/renderer/plainTextRenderer.tsx
  packages/gist-wsv/src/components/visualizer/renderer/proportionTextRenderer.tsx
  packages/gist-wsv/src/components/visualizer/renderer/rankTextRenderer.tsx
  packages/gist-wsv/src/components/visualizer/renderer/renderer.tsx
  packages/gist-wsv/src/components/visualizer/renderer/rendererList.ts
  packages/gist-wsv/src/components/visualizer/renderer/trendTextRenderer.tsx
  packages/gist-wsv/src/components/visualizer/renderer/valueTextRenderer.tsx
  packages/gist-wsv/src/components/visualizer/types.ts
  packages/gist-wsv/src/components/visualizer/utils/fuzzySearch.ts
  packages/gist-wsv/src/components/visualizer/utils/postProcess.ts
  packages/gist-wsv/src/components/visualizer/utils/useTrack.ts
  packages/gist-wsv/src/components/visualizer/utils/utils.ts
  packages/gist-wsv/src/components/visualizer/widgets/fallbackVis.tsx
  packages/gist-wsv/src/components/visualizer/widgets/hoverText.tsx
  packages/gist-wsv/src/components/visualizer/wordScaleVis/chartList.ts
  packages/gist-wsv/src/components/visualizer/wordScaleVis/glyphMaxMin.tsx
  packages/gist-wsv/src/components/visualizer/wordScaleVis/glyphText.tsx
  packages/gist-wsv/src/components/visualizer/wordScaleVis/hStackedBarChart.tsx
  packages/gist-wsv/src/components/visualizer/wordScaleVis/interface/SimpleBar.tsx
  packages/gist-wsv/src/components/visualizer/wordScaleVis/interface/SimpleLine.tsx
  packages/gist-wsv/src/components/visualizer/wordScaleVis/interface/SimpleMaxMin.tsx
  packages/gist-wsv/src/components/visualizer/wordScaleVis/interface/SimpleStackedBar.tsx
  packages/gist-wsv/src/components/visualizer/wordScaleVis/interface/index.ts
  packages/gist-wsv/src/components/visualizer/wordScaleVis/interface/types.ts
  packages/gist-wsv/src/components/visualizer/wordScaleVis/lineChart.tsx
  packages/gist-wsv/src/components/visualizer/wordScaleVis/vBarChart.tsx
  packages/gist-wsv/src/index.ts
  packages/gist-wsv/src/main.tsx
  packages/gist-wsv/src/style/page.css
  packages/gist-wsv/tsconfig.app.json
  packages/gist-wsv/tsconfig.json
  packages/gist-wsv/tsconfig.node.json
  packages/gist-wsv/vite.config.js
  packages/gist-wsv/vite.config.ts
  pnpm-lock.yaml
  site/package.json
  site/src/App.tsx
  site/src/demo/GistTest.tsx
  site/src/types/gist-wsv.d.ts
Labels: Chore - Refactor ⌨️

#53 add Jest and Babel configuration and tests; fix errors when running t…
  packages/gist-wsv/README.md
  packages/gist-wsv/babel.config.cjs
  packages/gist-wsv/jest.config.cjs
  packages/gist-wsv/package.json
  packages/gist-wsv/src/__mocks__/fileMock.js
  packages/gist-wsv/src/components/visualizer/utils/__tests__/fuzzySearch.test.ts
  packages/gist-wsv/src/components/visualizer/utils/__tests__/postProcess.test.ts
  packages/gist-wsv/src/components/visualizer/utils/__tests__/utils.test.ts
  packages/gist-wsv/src/components/visualizer/utils/postProcess.ts
  packages/gist-wsv/src/components/visualizer/utils/utils.ts
  packages/gist-wsv/src/setupTests.ts
  packages/gist-wsv/tsconfig.app.json
  packages/gist-wsv/tsconfig.json
  pnpm-lock.yaml
Labels: Chore - Refactor ⌨️

#52 Bugfix:wrong url and missing lodash dependency
  packages/gist-wsv/package.json
  pnpm-lock.yaml
  site/.env.SAMPLE
Labels: Bug 🐛

#59 Simple UI changes and element extraction
  site/src/App.tsx
  site/src/demo/Demo.tsx
  site/src/demo/LLMConf.tsx
  site/src/demo/commonElement/menuBar.tsx
  site/src/demo/pipeline/DemoPipeline.tsx
  site/src/userstudy/homePage.tsx
Labels: Area - Site

#64 Bugfix(bibtex.tsx): Extra html tags when copying BibTex
  site/src/introductionPage/component/bibtex.tsx
Labels: Bug 🐛

#67 Refactor/vake/rename fields in dataspec
  packages/gist-wsv/__tests__/postProcess.test.ts
  packages/gist-wsv/__tests__/utils.test.ts
  packages/gist-wsv/src/components/types.ts
  packages/gist-wsv/src/components/wordScaleVis/glyphMaxMin.tsx
  packages/gist-wsv/src/components/wordScaleVis/glyphText.tsx
  packages/gist-wsv/src/components/wordScaleVis/hStackedBarChart.tsx
  packages/gist-wsv/src/components/wordScaleVis/interface/SimpleBar.tsx
  packages/gist-wsv/src/components/wordScaleVis/interface/SimpleLine.tsx
  packages/gist-wsv/src/components/wordScaleVis/interface/SimpleMaxMin.tsx
  packages/gist-wsv/src/components/wordScaleVis/interface/SimpleStackedBar.tsx
  packages/gist-wsv/src/components/wordScaleVis/lineChart.tsx
  packages/gist-wsv/src/components/wordScaleVis/vBarChart.tsx
  packages/gist-wsv/src/renderer/comparisonTextRenderer.tsx
  packages/gist-wsv/src/renderer/rankTextRenderer.tsx
  packages/gist-wsv/src/renderer/renderer.tsx
  packages/gist-wsv/src/renderer/trendTextRenderer.tsx
  packages/gist-wsv/src/utils/postProcess.ts
  packages/gist-wsv/src/utils/utils.ts
  site/src/demo/demoPage.tsx
  site/src/demo/pipeline/PipelineExplorer.tsx
  site/src/demo/pipeline/SpecEditor.tsx
  site/src/demo/pipeline/SpecProcessEditor.tsx
  site/src/introductionPage/component/pipelinePage.tsx
  site/src/introductionPage/introData.ts
  site/src/modules/llm/extractor/extractExtreme.ts
  site/src/modules/llm/extractor/extractProportion.ts
  site/src/modules/llm/extractor/extractor.ts
  site/src/modules/llm/extractor/utils.ts
  site/src/types/gist-wsv.d.ts
  site/src/userstudy/articles/articledata.ts
  site/src/userstudy/articles/unprocessed articles/article2.ts
  site/src/userstudy/articles/unprocessed articles/article3.ts
  site/src/userstudy/articles/unprocessed articles/article4.ts
  site/src/userstudy/articles/unprocessed articles/article5.ts
  site/src/userstudy/articles/unprocessed articles/article6.ts
Labels: Chore - Refactor ⌨️

#69 Modification of miscellaneous items on the introduction page
  site/src/introductionPage/IntroPage.tsx
  site/src/introductionPage/IntroPageCSS.tsx
  site/src/introductionPage/component/pipelinePage.tsx
Labels: Area - Site

#77 Fix bidirectional highlight broken for vertical bar chart
  packages/gist-wsv/src/components/wordScaleVis/vBarChart.tsx
Labels: Bug 🐛, Area - Visualizer

#75 Modification of prompt
  site/src/modules/llm/discoverer/discoverer.ts
  site/src/modules/llm/visKB.ts
Labels: Bug 🐛, Area - Discoverer
